# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20160914_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_read', 'Can read'), ('can_commetn', 'Can comment'))},
        ),
    ]
